"""added_users_table

Revision ID: 22835d4b1145
Revises: d0026bc88385
Create Date: 2023-03-03 14:15:35.914358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22835d4b1145'
down_revision = 'd0026bc88385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('addr', sa.String(length=200), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
